### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by JaynouOliver** [shreyash321/Hindi_Benchmark_dataset#1]
with this dataset today, I was able to benchmark my LLM model transtokenized and finetuned on HIndi - thanks

https://huggingface.co/subhrokomol/Mistral-7B-Instruct-v0.3-transtokenized

**Comment by shreyash321** [comment]
Welcome bro , glad to see it helped you , do follow me for more such updates on hugging face 

https://huggingface.co/DrDrek
